### PR TITLE
Allow users to suppress any built-in logged keys through configuration

### PR DESCRIPTION
**Pull request by trumant**
For example, to never log the keys "api_version" and "log_type", a consuming
application would use a configuration of:

config :plug_logger_json,
  suppressed_keys: ["api_version", "log_type"]

### CODE REVIEW

**Comment by johnkelly** [comment]
@trumant 
Thank you for the contribution. I agree that this feature would be useful to reduce the verbosity of the logs. It looks like some test broke from this change. Can you update the tests?

**Comment by trumant** [comment]
I believe the tests were broken on master prior to my change.

**Comment by johnkelly** [comment]
Hmm looks like Plug 1.3 -> 1.4 broke the tests

**Comment by johnkelly** [comment]
@trumant, I've merged your changes into master. The build failure now is only for the elixir 1.3 build and OTP 20 combo which are not compatible with each other. Thanks again for your contribution. It will be included in the next minor version.

**Pull request merged**
